---
- hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
    - name: install git
      apt: name=git update_cache=yes state=latest