- name: launch a compute instance
  hosts: localhost
  tasks:
  - os_server:
         state: present
         # auth:
         #   auth_url: https://your-server.your.domain.com:5000/v2.0
         #   username: your-user
         #   password: your-password
         #   project_name: your-project
         name: my-instance
         image: ubuntu-14.04-server-amd64
         key_name: demo-keypair
         timeout: 800
         flavor: m1.small
         nics:
           - net-name: demo-network